# Configuração principal
server:
 port: 8081
# ElasticSearch configs
spring.data.elasticsearch.properties.transport.tcp.connect_timeout: 120s

# Configurações do service-discovery
eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
